spring:
  jpa:
    show-sql: true
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.transaction: TRACE
    org.springframework.jpa: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG